import { Application } from '@/types/application';

const generateId = () => `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

export const getDemoData = (): Application[] => {
  const now = new Date();
  
  const getDate = (daysAgo: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().split('T')[0];
  };

  return [
    {
      id: generateId() + '-1',
      company: 'Google',
      role: 'Software Engineer Intern',
      applicationLink: 'https://careers.google.com',
      location: 'Mountain View, CA (Hybrid)',
      appliedDate: getDate(14),
      status: 'Interview Scheduled',
      notes: 'First round technical interview scheduled. Need to brush up on graph algorithms and dynamic programming.',
      salary: '$52/hr',
      source: 'Company Website',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-2',
      company: 'Microsoft',
      role: 'Software Engineering Intern',
      applicationLink: 'https://careers.microsoft.com',
      location: 'Redmond, WA',
      appliedDate: getDate(25),
      status: 'Offer',
      notes: 'Received verbal offer! Waiting for the official letter. Team focuses on Azure infrastructure.',
      salary: '$48/hr + Housing Stipend',
      source: 'Referral',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-3',
      company: 'Amazon',
      role: 'SDE Intern',
      applicationLink: 'https://amazon.jobs',
      location: 'Seattle, WA',
      appliedDate: getDate(5),
      status: 'OA Received',
      notes: 'Received OA part 1. Contains 2 coding questions (easy/medium). Deadline is in 3 days.',
      salary: '',
      source: 'LinkedIn',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-4',
      company: 'Meta',
      role: 'Front-End Engineer Intern',
      applicationLink: 'https://metacareers.com',
      location: 'Menlo Park, CA',
      appliedDate: getDate(40),
      status: 'Rejected',
      notes: 'Standard rejection email. Did not pass the resume screening stage.',
      salary: '',
      source: 'Company Website',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-5',
      company: 'Netflix',
      role: 'Core Engineering Intern',
      applicationLink: 'https://jobs.netflix.com',
      location: 'Los Gatos, CA',
      appliedDate: getDate(1),
      status: 'Applied',
      notes: 'Cold emailed a recruiter I found on LinkedIn. Let\'s see if they respond.',
      salary: '',
      source: 'Cold Email',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-6',
      company: 'Stripe',
      role: 'Software Engineer Intern',
      applicationLink: 'https://stripe.com/jobs',
      location: 'Remote',
      appliedDate: getDate(20),
      status: 'Rejected',
      notes: 'Completed the OA but wasn\'t selected for the final loop.',
      salary: '$55/hr',
      source: 'Referral',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-7',
      company: 'Notion',
      role: 'Product Engineer Intern',
      applicationLink: '',
      location: 'San Francisco, CA',
      appliedDate: getDate(8),
      status: 'OA Received',
      notes: 'Take-home assignment received. Needs to build a mini rich-text editor in React.',
      salary: '$50/hr',
      source: 'Other',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-8',
      company: 'Apple',
      role: 'Hardware/Software Intern',
      applicationLink: 'https://apple.com/jobs',
      location: 'Cupertino, CA',
      appliedDate: getDate(12),
      status: 'Applied',
      notes: 'Applied through the general university portal. Heard they take a long time to get back.',
      salary: '',
      source: 'Company Website',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-9',
      company: 'Spotify',
      role: 'Backend Intern',
      applicationLink: 'https://spotifyjobs.com',
      location: 'New York, NY',
      appliedDate: getDate(3),
      status: 'Applied',
      notes: 'Found the listing on LinkedIn. Tailored my resume to highlight my Java Spring Boot experience.',
      salary: '',
      source: 'LinkedIn',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-10',
      company: 'Vercel',
      role: 'Frontend Engineering Intern',
      applicationLink: '',
      location: 'Remote',
      appliedDate: getDate(18),
      status: 'Interview Scheduled',
      notes: 'Final round with the engineering manager on Friday.',
      salary: '$45/hr',
      source: 'Referral',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-11',
      company: 'Airbnb',
      role: 'Software Engineering Intern',
      applicationLink: '',
      location: 'San Francisco, CA',
      appliedDate: getDate(30),
      status: 'Offer',
      notes: 'Offer signed! Really excited about their tech stack and culture.',
      salary: '$50/hr + Benefits',
      source: 'Company Website',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-12',
      company: 'Uber',
      role: 'Data Science Intern',
      applicationLink: '',
      location: 'San Francisco, CA',
      appliedDate: getDate(22),
      status: 'Rejected',
      notes: 'Didn\'t make it past the technical phone screen. Need to improve SQL skills.',
      salary: '',
      source: 'Internshala',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-13',
      company: 'Discord',
      role: 'Infrastructure Intern',
      applicationLink: '',
      location: 'San Francisco, CA',
      appliedDate: getDate(7),
      status: 'Applied',
      notes: 'Cold emailed an engineering manager.',
      salary: '',
      source: 'Cold Email',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-14',
      company: 'Figma',
      role: 'Software Engineer Intern',
      applicationLink: '',
      location: 'San Francisco, CA',
      appliedDate: getDate(15),
      status: 'OA Received',
      notes: 'C++ OA received. They are looking for strong graphics knowledge.',
      salary: '$55/hr',
      source: 'LinkedIn',
      lastUpdated: new Date().toISOString(),
    },
    {
      id: generateId() + '-15',
      company: 'Robinhood',
      role: 'Backend Intern',
      applicationLink: '',
      location: 'Menlo Park, CA',
      appliedDate: getDate(28),
      status: 'Interview Scheduled',
      notes: 'Passed the Karat interview. Next round is system design.',
      salary: '$48/hr',
      source: 'Referral',
      lastUpdated: new Date().toISOString(),
    }
  ];
};
